name: Add Label To Contributor PRs

on:
  pull_request:
    types: opened

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(context))
      - run: echo ${{ github.event.pull_request.author_association }}
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ github.event.pull_request.author_association == 'CONTRIBUTOR' || github.event.pull_request.author_association == 'NONE' }}
        with:
          labels: "from:contributor"
