name: Add Label To Contributor PRs

on:
  pull_request:
    types: opened

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ github.event.pull_request.author_association }}
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ github.event.pull_request.author_association == 'CONTRIBUTOR' }}
        with:
          labels: "from:contributor"
